# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push:
    branches: [main]
env:
  BUCKET_NAME : "BUCKET-NAME"
  AWS_REGION : "AWS-REGION"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: self-hosted
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::230020307145:role/actionrole4ec2
          role-session-name: samplerolesession
          aws-region: us-east-1
      # Upload a file to AWS s3
      - name: create an ec2 instance
        run: |
          aws ec2 run-instances \
          --image-id ami-084568db4383264d4 \
          --count 1 \
          --instance-type t2.micro \
          --key-name mongo-server \
          --security-group-ids sg-0de3ca9ca723c8d7c \
          --subnet-id subnet-004445367572dadfe \
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=OIDC-INSTANCE}]'

